// One-time build script for the vendored CodeMirror bundle.
// Usage: npm ci && npm run build
// Output is committed to git; end users of talkpipe never need Node.

import { build } from "esbuild";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "src", "talkpipe", "app", "static", "workbench", "vendor");

await build({
  entryPoints: [join(here, "src", "cm.js")],
  bundle: true,
  format: "esm",
  minify: true,
  outfile: join(outDir, "codemirror.js"),
  logLevel: "info",
});

// Aggregate the licenses of every bundled package (all MIT) so the vendored
// artifact ships with its license texts, per the project's open-source policy.
const pkgs = [];
const nodeModules = join(here, "node_modules");
for (const scope of ["@codemirror", "@lezer", "@marijn", "style-mod", "w3c-keyname", "crelt"]) {
  const scopeDir = join(nodeModules, scope);
  if (!existsSync(scopeDir)) continue;
  if (scope.startsWith("@")) {
    for (const name of readdirSync(scopeDir)) pkgs.push(join(scopeDir, name));
  } else {
    pkgs.push(scopeDir);
  }
}

let licenses = "Licenses for packages bundled into codemirror.js\n" +
  "Generated by frontend/build.mjs\n";
for (const dir of pkgs) {
  const pkgJsonPath = join(dir, "package.json");
  if (!existsSync(pkgJsonPath)) continue;
  const meta = JSON.parse(readFileSync(pkgJsonPath, "utf8"));
  const licFile = ["LICENSE", "LICENSE.md", "LICENSE.txt"]
    .map((f) => join(dir, f))
    .find(existsSync);
  licenses += `\n${"=".repeat(72)}\n${meta.name} ${meta.version} — ${meta.license}\n${"=".repeat(72)}\n`;
  if (licFile) licenses += readFileSync(licFile, "utf8");
}
writeFileSync(join(outDir, "LICENSES.txt"), licenses);
console.log(`Wrote ${join(outDir, "LICENSES.txt")} (${pkgs.length} packages)`);
